graph LR
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.6 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.7 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|4.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.10 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.12 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.13 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_3["wcag-2.2 SC 3.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_4["wcag-2.2 SC 3.2.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_3["wcag-2.2 SC 3.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_4["wcag-2.2 SC 3.3.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_8["wcag-2.2 SC 3.3.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|4.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|4.1.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_3["wcag-2.2 SC 4.1.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_6["wcag-2.2 SC 1.2.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_7["wcag-2.2 SC 1.2.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_8["wcag-2.2 SC 1.2.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.2.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_9["wcag-2.2 SC 1.2.9"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.3.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_6["wcag-2.2 SC 1.3.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_6["wcag-2.2 SC 1.4.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_7["wcag-2.2 SC 1.4.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_8["wcag-2.2 SC 1.4.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_9["wcag-2.2 SC 1.4.9"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|1.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_3["wcag-2.2 SC 2.1.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_3["wcag-2.2 SC 2.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_4["wcag-2.2 SC 2.2.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_5["wcag-2.2 SC 2.2.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_6["wcag-2.2 SC 2.2.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_2["wcag-2.2 SC 2.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_3["wcag-2.2 SC 2.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_8["wcag-2.2 SC 2.4.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_9["wcag-2.2 SC 2.4.9"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_10["wcag-2.2 SC 2.4.10"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_12["wcag-2.2 SC 2.4.12"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_13["wcag-2.2 SC 2.4.13"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_5["wcag-2.2 SC 2.5.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_6["wcag-2.2 SC 2.5.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|2.5.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_3["wcag-2.2 SC 3.1.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_4["wcag-2.2 SC 3.1.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_5["wcag-2.2 SC 3.1.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.1.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_6["wcag-2.2 SC 3.1.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_3["wcag-2.2 SC 3.2.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_4["wcag-2.2 SC 3.2.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_5["wcag-2.2 SC 3.2.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_3["wcag-2.2 SC 3.3.3"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_4["wcag-2.2 SC 3.3.4"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_5["wcag-2.2 SC 3.3.5"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_6["wcag-2.2 SC 3.3.6"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_8["wcag-2.2 SC 3.3.8"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|3.3.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_9["wcag-2.2 SC 3.3.9"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|4.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_A_1_1_1["atag-2.0 SC A.1.1.1: Web-Based Accessible (WCAG)"] -->|4.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_4_1_3["wcag-2.2 SC 4.1.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.6 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.7 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|4.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.10 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.12 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.13 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_3["wcag-2.2 SC 3.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_4["wcag-2.2 SC 3.2.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_3["wcag-2.2 SC 3.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_4["wcag-2.2 SC 3.3.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_8["wcag-2.2 SC 3.3.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|4.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|4.1.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_3["wcag-2.2 SC 4.1.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_6["wcag-2.2 SC 1.2.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_7["wcag-2.2 SC 1.2.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_8["wcag-2.2 SC 1.2.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.2.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_9["wcag-2.2 SC 1.2.9"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.3.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_6["wcag-2.2 SC 1.3.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_6["wcag-2.2 SC 1.4.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_7["wcag-2.2 SC 1.4.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_8["wcag-2.2 SC 1.4.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_9["wcag-2.2 SC 1.4.9"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|1.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_3["wcag-2.2 SC 2.1.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_3["wcag-2.2 SC 2.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_4["wcag-2.2 SC 2.2.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_5["wcag-2.2 SC 2.2.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_6["wcag-2.2 SC 2.2.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_2["wcag-2.2 SC 2.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_3["wcag-2.2 SC 2.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_8["wcag-2.2 SC 2.4.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_9["wcag-2.2 SC 2.4.9"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_10["wcag-2.2 SC 2.4.10"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_12["wcag-2.2 SC 2.4.12"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_13["wcag-2.2 SC 2.4.13"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_5["wcag-2.2 SC 2.5.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_6["wcag-2.2 SC 2.5.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|2.5.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_3["wcag-2.2 SC 3.1.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_4["wcag-2.2 SC 3.1.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_5["wcag-2.2 SC 3.1.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.1.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_6["wcag-2.2 SC 3.1.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_3["wcag-2.2 SC 3.2.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_4["wcag-2.2 SC 3.2.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_5["wcag-2.2 SC 3.2.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_3["wcag-2.2 SC 3.3.3"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_4["wcag-2.2 SC 3.3.4"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_5["wcag-2.2 SC 3.3.5"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_6["wcag-2.2 SC 3.3.6"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_8["wcag-2.2 SC 3.3.8"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|3.3.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_3_9["wcag-2.2 SC 3.3.9"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|4.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_B_1_1_1["atag-2.0 SC B.1.1.1: Content Auto-Generation After Authoring Sessions (WCAG)"] -->|4.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_4_1_3["wcag-2.2 SC 4.1.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.3 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.4 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.6 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.1 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.7 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|4.1.2 (wcag22-level-a-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.10 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.12 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.13 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.5 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.11 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_2["wcag-2.2 SC 3.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_3["wcag-2.2 SC 3.2.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_4["wcag-2.2 SC 3.2.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.6 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_2_6["wcag-2.2 SC 3.2.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.1 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_1["wcag-2.2 SC 3.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_2["wcag-2.2 SC 3.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_3["wcag-2.2 SC 3.3.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.4 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_4["wcag-2.2 SC 3.3.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.7 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_7["wcag-2.2 SC 3.3.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.3.8 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_3_3_8["wcag-2.2 SC 3.3.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|4.1.2 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_2["wcag-2.2 SC 4.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|4.1.3 (wcag22-level-aa-minus-4.1.1)| sc_wcag_2_2_4_1_3["wcag-2.2 SC 4.1.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_1_1["wcag-2.2 SC 1.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_1["wcag-2.2 SC 1.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_2["wcag-2.2 SC 1.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_3["wcag-2.2 SC 1.2.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_4["wcag-2.2 SC 1.2.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_5["wcag-2.2 SC 1.2.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_6["wcag-2.2 SC 1.2.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_7["wcag-2.2 SC 1.2.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_8["wcag-2.2 SC 1.2.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.2.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_2_9["wcag-2.2 SC 1.2.9"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_1["wcag-2.2 SC 1.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_2["wcag-2.2 SC 1.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_3["wcag-2.2 SC 1.3.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_4["wcag-2.2 SC 1.3.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_5["wcag-2.2 SC 1.3.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.3.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_3_6["wcag-2.2 SC 1.3.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_1["wcag-2.2 SC 1.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_2["wcag-2.2 SC 1.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_3["wcag-2.2 SC 1.4.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_4["wcag-2.2 SC 1.4.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_5["wcag-2.2 SC 1.4.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_6["wcag-2.2 SC 1.4.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_7["wcag-2.2 SC 1.4.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_8["wcag-2.2 SC 1.4.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_9["wcag-2.2 SC 1.4.9"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_10["wcag-2.2 SC 1.4.10"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_11["wcag-2.2 SC 1.4.11"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_12["wcag-2.2 SC 1.4.12"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|1.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_1_4_13["wcag-2.2 SC 1.4.13"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_1["wcag-2.2 SC 2.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_2["wcag-2.2 SC 2.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_3["wcag-2.2 SC 2.1.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_1_4["wcag-2.2 SC 2.1.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_1["wcag-2.2 SC 2.2.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_2["wcag-2.2 SC 2.2.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_3["wcag-2.2 SC 2.2.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_4["wcag-2.2 SC 2.2.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_5["wcag-2.2 SC 2.2.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.2.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_2_6["wcag-2.2 SC 2.2.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.3.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_1["wcag-2.2 SC 2.3.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.3.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_2["wcag-2.2 SC 2.3.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.3.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_3_3["wcag-2.2 SC 2.3.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_1["wcag-2.2 SC 2.4.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_2["wcag-2.2 SC 2.4.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_3["wcag-2.2 SC 2.4.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_4["wcag-2.2 SC 2.4.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_5["wcag-2.2 SC 2.4.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_6["wcag-2.2 SC 2.4.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_7["wcag-2.2 SC 2.4.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_8["wcag-2.2 SC 2.4.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.9 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_9["wcag-2.2 SC 2.4.9"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.10 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_10["wcag-2.2 SC 2.4.10"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.11 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_11["wcag-2.2 SC 2.4.11"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.12 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_12["wcag-2.2 SC 2.4.12"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.4.13 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_4_13["wcag-2.2 SC 2.4.13"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_1["wcag-2.2 SC 2.5.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_2["wcag-2.2 SC 2.5.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_3["wcag-2.2 SC 2.5.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_4["wcag-2.2 SC 2.5.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_5["wcag-2.2 SC 2.5.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_6["wcag-2.2 SC 2.5.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.7 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_7["wcag-2.2 SC 2.5.7"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|2.5.8 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_2_5_8["wcag-2.2 SC 2.5.8"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_1["wcag-2.2 SC 3.1.1"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.2 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_2["wcag-2.2 SC 3.1.2"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.3 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_3["wcag-2.2 SC 3.1.3"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.4 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_4["wcag-2.2 SC 3.1.4"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.5 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_5["wcag-2.2 SC 3.1.5"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.1.6 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_1_6["wcag-2.2 SC 3.1.6"]
    sc_atag_2_0_B_1_2_1["atag-2.0 SC B.1.2.1: Restructuring and Recoding Transformations (WCAG)"] -->|3.2.1 (wcag22-level-aaa-minus-4.1.1)| sc_wcag_2_2_3_2_1["wcag-2.2 SC 3.2.1"]
