graph LR
    html_living_standard["HTML Living Standard"]
    css_overview["W3C CSS Specifications Overview"]
    wcag_22["WCAG 2.2"]
    html_semantics["The elements of HTML"]
    html_semantics -->|part_of| html_living_standard
    html_semantics -->|supports_outcome_for| wcag_22
    html_forms["Forms"]
    html_forms -->|part_of| html_living_standard
    html_forms -->|supports_outcome_for| wcag_22
    html_interaction["User interaction"]
    html_interaction -->|part_of| html_living_standard
    html_interaction -->|supports_outcome_for| wcag_22
    html_dom["The HTML syntax and DOM"]
    html_dom -->|part_of| html_living_standard
    html_dom -->|supports_outcome_for| wcag_22
    html_rendering["Rendering"]
    html_rendering -->|part_of| html_living_standard
    html_rendering -->|supports_outcome_for| wcag_22
    html_structured_data["Tables and structured data"]
    html_structured_data -->|part_of| html_living_standard
    html_structured_data -->|supports_outcome_for| wcag_22
    css_css_color["CSS Color"]
    css_css_color -->|part_of| css_overview
    css_css_color -->|supports_outcome_for| wcag_22
    css_css_ui["CSS Basic User Interface"]
    css_css_ui -->|part_of| css_overview
    css_css_ui -->|supports_outcome_for| wcag_22
    css_mediaqueries["Media Queries"]
    css_mediaqueries -->|part_of| css_overview
    css_mediaqueries -->|supports_outcome_for| wcag_22
    css_css_overflow["CSS Overflow"]
    css_css_overflow -->|part_of| css_overview
    css_css_overflow -->|supports_outcome_for| wcag_22
    css_css_writing_modes["CSS Writing Modes"]
    css_css_writing_modes -->|part_of| css_overview
    css_css_writing_modes -->|supports_outcome_for| wcag_22
    css_css_text["CSS Text"]
    css_css_text -->|part_of| css_overview
    css_css_text -->|supports_outcome_for| wcag_22
    css_css_display["CSS Display"]
    css_css_display -->|part_of| css_overview
    css_css_display -->|supports_outcome_for| wcag_22
    css_css_flexbox["CSS Flexible Box Layout"]
    css_css_flexbox -->|part_of| css_overview
    css_css_flexbox -->|supports_outcome_for| wcag_22
    css_css_grid["CSS Grid Layout"]
    css_css_grid -->|part_of| css_overview
    css_css_grid -->|supports_outcome_for| wcag_22
    css_css_transitions["CSS Transitions"]
    css_css_transitions -->|part_of| css_overview
    css_css_transitions -->|supports_outcome_for| wcag_22
    css_css_animations["CSS Animations"]
    css_css_animations -->|part_of| css_overview
    css_css_animations -->|supports_outcome_for| wcag_22
    css_css_scroll_snap["CSS Scroll Snap"]
    css_css_scroll_snap -->|part_of| css_overview
    css_css_scroll_snap -->|supports_outcome_for| wcag_22
